name: Project Testing
run-name: ${{ github.actor }} is testing his project....

on:
  push:
    branches:
    - main

jobs:
  project-feedback:
    runs-on: ubuntu-latest
    
    steps:
    - name: "Kaggle Username Check"
      env: 
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
      if: ${{ env.KAGGLE_USERNAME == '' }}
      run: 'echo "echo KAGGLE_USERNAME is missing. Go to \"Settings \> Environments \" to create it."'
    - name: "Check Kaggle Key"
      env:
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      if: ${{ env.KAGGLE_KEY == '' }}
      run: 'echo "echo KAGGLE_KEY is missing. Go to \"Settings \> Environments \" to create it."'

    - name: Checkout
      uses: actions/checkout@v3

    # Install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    # pip install
    - name: Install packages
      run: pip install -r requirements.txt
    
    - name: Kaggle auth
      shell: bash
      run: |
        echo '{
          "username": "${{ secrets.KAGGLE_USERNAME }}",
          "key": "${{ secrets.KAGGLE_KEY }}"
        }' > kaggle.json
        mv kaggle.json ~/project/
        chmod 600 ~/project/kaggle.json
        echo "Login to Kaggle successful"

    # Run exercise feedback
    - name: Make test runnable
      run: chmod +x ./project/tests.sh
    - name: Run tests
      run: |
        ./project/tests.sh
